version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 16  
  pre_build:
    commands:
      - aws s3 cp s3://starsteamapi-filecontents/.env ./
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'