version: 0.2
phases:
  install:
    commands:
      - sudo yum update
      - sudo yum install -y nodejs 
      - node --version
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'