version: 0.2
phases:
  install:
    commands:
      - sudo yum remove -y nodejs npm
      - curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
      - node --version
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'